"""Clinical-imaging inference contract.

Weights are intentionally not bundled. A validated model, dataset, calibration,
DICOM policy, and clinical commissioning are required before enabling inference.
"""
from __future__ import annotations

import os
from dataclasses import dataclass


@dataclass(frozen=True)
class InferenceResult:
    status: str
    model_id: str
    findings: tuple[str, ...]
    confidence: float | None
    clinical_decision: bool = False


class ImagingInference:
    def __init__(self, model_id: str | None = None, weights_path: str | None = None):
        self.model_id = model_id or os.getenv("CV_MODEL_ID", "unvalidated-not-loaded")
        self.weights_path = weights_path or os.getenv("CV_WEIGHTS_PATH", "")

    @property
    def enabled(self) -> bool:
        return bool(self.weights_path and os.path.isfile(self.weights_path) and os.getenv("CV_INFERENCE_ENABLED", "false").casefold() == "true")

    def predict(self, image_bytes: bytes) -> InferenceResult:
        if not image_bytes or len(image_bytes) > 25 * 1024 * 1024:
            raise ValueError("image payload is empty or exceeds the limit")
        if not self.enabled:
            return InferenceResult("disabled", self.model_id, (), None, False)
        # Model loading and preprocessing must be supplied only after clinical
        # validation; no diagnosis is generated by this safe contract.
        return InferenceResult("model_adapter_pending_validation", self.model_id, (), None, False)
