apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: tabeeby-authz
  namespace: tabeeby-healthcare
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/tabeeby-healthcare/sa/*"]
    to:
    - operation:
        methods: ["GET", "POST", "PUT", "DELETE"]
        paths: ["/api/v1/*"]
