apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: tabeeby-gateway
  namespace: tabeeby-healthcare
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: tabeeby-tls
    hosts:
    - "*.tabeeby.health"
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.tabeeby.health"
    tls:
      httpsRedirect: true
